version: '3.5'
services:
  web:
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    links:
      - backend
      - frontend
  backend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      - RAILS_ENV=development
      - DB_USER=webapp
      - DB_PASS=p@ssw0rd
      - DB_NAME=webapp
      - DB_HOST=db
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:delegated
  frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-frontend
    environment:
      - BACKEND_ENDPOINT=http://backend:3000
    links:
      - db
      - backend
    ports:
      - "3001:3000"
    volumes:
      - '/app/node_modules'
      - ./frontend:/app:delegated
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: webapp
    volumes:
      - ./data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
