AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
